name: Run Python Scripts

on:
  schedule:
    - cron: '0 * * * *' # Esto ejecuta los scripts cada hora
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7' # Elige la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asegúrate de tener un archivo requirements.txt con tus dependencias

      - name: Run Python script 1
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python3 json-services-cards-bienestar.py # Reemplaza 'script1.py' con el nombre de tu primer archivo

      - name: Run Python script 2
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python3 json-services-cards-gestion-comunidades.py # Reemplaza 'script2.py' con el nombre de tu segundo archivo

      - name: Run Python script 3
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python json-services-cards-voluntariado-experiencial.py # Reemplaza 'script3.py' con el nombre de tu tercer archivo

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m 'Update JSON data'
          git push


