name: Run Python Scripts

on:
  schedule:
    - cron: '0 * * * *' # Esto ejecuta los scripts cada hora
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7' # Especifica la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asegúrate de tener un archivo requirements.txt con tus dependencias

      - name: Set up Google Sheets credentials
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          echo "${GOOGLE_SHEETS_CREDENTIALS}" > client_secrets.json

      - name: Run Python script 1
        run: |
          python json-services-cards-bienestar.py

      - name: Run Python script 2
        run: |
          python json-services-cards-gestion-comunidades.py

      - name: Run Python script 3
        run: |
          python json-services-cards-voluntariado-experiencial.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m 'Update JSON data'
          git push
